#配置服务器端口，默认为8080;用户回话session过期时间，以秒为单位
server:
  port: 10086

#关于引用哪个yml，可以减少开发时的配置情况
spring:
  profiles:
    active:


student:
  name: aboy
  age: 25
  #course: {"chinese" : "你好，世界！" , "English" : "Hello World!"}

person:
  name: aboy
  age: 26
  course: {"chinese" : "你好，世界！" , "English" : "Hello World!"}
  say:
    "chinese" : "你好，世界！"
    "English" : "Hello World!"
  fruits:
    - "apple"
    - "banana"
  skillList:
    - "name" : "sing"
      "level" : 5
    - "name" : "draw"
      "level" : 10

